name: Feature request
description: Suggest an idea for this project
title: "[Feature] "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem description
      description: Please describe the problem you are trying to solve/improve upon with this feature request.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Suggested solution
      description: What would you suggest to implement to solve this problem?
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative solutions
      description: What alternative solutions have you considered, and why did you not choose them?
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context / information
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
